baseURL = "https://blog.blvckleg.dev/"
languageCode = "en_us"
title = "blog | blvckleg.dev"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "sanriodev"
  description = "typescript wizard 🧙"
  github = "sanriodev"
  twitter = "blvckleg"
  linkedin = "Matteo Juen"
  instagram = "sanrio_bf"
  url = "https://blvckleg.dev"
  keywords = "blog"
  rss = true
  lastmod = true
  userStatusEmoji = "🤓"
  favicon = "/images/favicon.ico"
  avatar = "https://avatars.githubusercontent.com/sanriodev"
  headerIcon = "/images/github-mark-white.png"
  location = "Austria"
  enableGitalk = true

  [params.gitalk]
    clientID = "Iv23ct9oFW1JsyqzN592"
    clientSecret = "SECRET_PLACEHOLDER"
    repo = "blog.blvckleg.dev"
    owner = "sanriodev"
    admin = "sanriodev"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 30
    pagerDirection = "last"
    createIssueManually = false
    distractionFreeMode = false

  [[params.links]]
    title = "Link2"
    href = "https://blvckleg.dev"
    icon = "https://avatars.githubusercontent.com/sanriodev"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
