baseURL = "https://blog.blvckleg.dev/"
languageCode = "en_us"
title = "blog | blvckleg.dev"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "sanriodev"
  description = "typescript wizard 🧙"
  github = "sanriodev"
  twitter = "blvckleg"
  linkedin = "Matteo Juen"
  instagram = "sanrio_bf"
  url = "https://blvckleg.dev"
  keywords = "blog"
  rss = true
  lastmod = true
  userStatusEmoji = "🤓"
  favicon = "/images/favicon.ico"
  avatar = "https://avatars.githubusercontent.com/sanriodev"
  headerIcon = "/images/github-mark-white.png"
  location = "Austria"

  [[params.links]]
    title = "Link2"
    href = "https://blvckleg.dev"
    icon = "https://avatars.githubusercontent.com/sanriodev"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]